export const SET_COORDINATE = 'SET_COORDINATE'
export const RESET_COORDINATE = 'RESET_COORDINATE'

export const SET_MAP_INITIALIZING = 'SET_MAP_INITIALIZING'
export const RESET_MAP_INITIALIZING = 'RESET_MAP_INITIALIZING'

export const SET_ADDRESS = 'SET_ADDRESS'
export const RESET_ADDRESS = 'RESET_ADDRESS'