export const SET_COORDINATE = 'SET_COORDINATE'
export const RESET_COORDINATE = 'RESET_COORDINATE'

export const SET_MAP_INITIALIZING = 'SET_MAP_INITIALIZING'
export const RESET_MAP_INITIALIZING = 'RESET_MAP_INITIALIZING'
